apiVersion: v1
kind: ConfigMap
metadata:
  name: pharmacy-config
  labels:
    app: pharmacy-claims-processing
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://postgres:5432/pharmacydb
        username: pharmacy_user
        password: pharmacy_pass
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
      bootstrap-servers: kafka:9092
      topic:
        claims: pharmacy-claims
        processed: processed-claims
        error: error-claims
    claims:
      retry-count: 3
    logging:
      level:
        root: INFO 